### ISSUE TITLE
Tests passing for incorrect implementation of logistic regression forward

### ISSUE THREAD

**Issue by sergiomarchio** [facundoq/simplenn#15]
Hi!

in exercise `11. Regresión Logística` the tests on the logistic forward implementation are passing even with a wrong implementation (applying bias before linear)

It may be because of the particular examples used for the test.

Thank you!

Edit: it is exercise 11 not 10

**Comment by facundoq** [comment]
Fixed by using a different number of outputs (3) and inputs (2), so that w*x gives a 3 element vector, and so b must have the same size. Now when applying the bias before the linear part you get an error because sizes don't match. Thanks for reporting!
